# Generated by Django 2.2 on 2019-05-15 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databasedaemon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroomactivity',
            old_name='classroom_umber',
            new_name='classroom_number',
        ),
    ]
