# Generated by Django 2.2 on 2019-05-18 16:11

import databasedaemon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databasedaemon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='email_domain',
            field=models.CharField(max_length=20, validators=[databasedaemon.models.email_domain_validator]),
        ),
    ]
