# Generated by Django 2.2 on 2019-05-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databasedaemon', '0002_auto_20190515_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='max_lesson_number',
            field=models.IntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='type',
            field=models.CharField(choices=[('лекционная', 'лекционная'), ('семинарская', 'семинарская'), ('лаборатория', 'лаборатория'), ('для сотрудников', 'для сотрудников')], default='семинарская', max_length=20),
        ),
        migrations.AlterField(
            model_name='classroomactivity',
            name='vacant',
            field=models.CharField(choices=[('свободна', 'свободна'), ('зарезервирована', 'зарезервирована'), ('занята', 'занята')], default='свободна', max_length=20),
        ),
    ]
